GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ2hhbXVkaXRoYSIsImlhdCI6MTYyNjAyOTYwMX0.wt7rJcD6MdH5zKbodk0qMhUWNOTvwLCg5vyzLKDcMYc

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Chamuditha"
}